version: "3.6"

services:

    flowable-idm-app:
        image: flowable/flowable-idm
        environment:
            - SERVER_PORT=8080
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://${PG_HOST}:5432/${PG_DB}
            - SPRING_DATASOURCE_USERNAME=${PG_USER}
            - SPRING_DATASOURCE_PASSWORD=${PG_PASS}
        ports:
            - 8080:8080
        entrypoint: ["java", "-jar", "app.war"]

    flowable-rest-app:
        image: flowable/flowable-rest
        environment:
            - SERVER_PORT=9977
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://${PG_HOST}:5432/${PG_DB}
            - SPRING_DATASOURCE_USERNAME=${PG_USER}
            - SPRING_DATASOURCE_PASSWORD=${PG_PASS}
            - FLOWABLE.REST.APP.ADMIN.USER-ID=rest-admin
            - FLOWABLE.REST.APP.ADMIN.PASSWORD=test
            - FLOWABLE.REST.APP.ADMIN.FIRST-NAME=Rest
            - FLOWABLE.REST.APP.ADMIN.LAST-NAME=Admin
        ports:
            - 9977:9977
        entrypoint: ["java", "-jar", "app.war"]

    flowable-task-app:
        image: flowable/flowable-task
        container_name: flowable-task
        depends_on:
            - flowable-idm-app
        environment:
            - SERVER_PORT=9999
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://${PG_HOST}:5432/${PG_DB}
            - SPRING_DATASOURCE_USERNAME=${PG_USER}
            - SPRING_DATASOURCE_PASSWORD=${PG_PASS}

            - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-app:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
            - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test
        ports:
            - 9999:9999
        entrypoint: ["java", "-jar", "app.war"]

    flowable-admin-app:
        image: flowable/flowable-admin
        depends_on:
            - flowable-idm-app
            - flowable-rest-app
        environment:
            - SERVER_PORT=9988
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://${PG_HOST}:5432/${PG_DB}
            - SPRING_DATASOURCE_USERNAME=${PG_USER}
            - SPRING_DATASOURCE_PASSWORD=${PG_PASS}

            - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-app:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8080/flowable-idm
            - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
            - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test

            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS=http://flowable-rest-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT=9977
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT=flowable-rest
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT=service

            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS=http://flowable-rest-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT=9977
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT=flowable-rest
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT=cmmn-api

            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS=http://flowable-task-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT=9999
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT=flowable-task
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT=app-api

            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS=http://flowable-rest-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT=9977
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT=flowable-rest
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT=dmn-api

            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS=http://flowable-rest-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT=9977
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT=flowable-rest
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT=form-api

            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS=http://flowable-rest-app
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT=9977
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT=flowable-rest
            - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT=content-api

        ports:
            - 9988:9988
        entrypoint: ["java", "-jar", "app.war"]

